package com.pwms.report.util;

import com.itextpdf.io.font.constants.StandardFonts;
import com.itextpdf.kernel.colors.ColorConstants;
import com.itextpdf.kernel.font.PdfFont;
import com.itextpdf.kernel.font.PdfFontFactory;
import com.itextpdf.kernel.pdf.PdfDocument;
import com.itextpdf.kernel.pdf.PdfWriter;
import com.itextpdf.layout.Document;
import com.itextpdf.layout.element.Cell;
import com.itextpdf.layout.element.Paragraph;
import com.itextpdf.layout.element.Table;
import com.itextpdf.layout.properties.TextAlignment;
import com.pwms.report.dto.ReportDTO;
import org.springframework.stereotype.Component;

import java.io.ByteArrayOutputStream;

@Component
public class PdfReportGenerator {

    public byte[] generate(ReportDTO r) {
        ByteArrayOutputStream out = new ByteArrayOutputStream();

        try (PdfWriter   writer = new PdfWriter(out);
             PdfDocument pdf    = new PdfDocument(writer);
             Document    doc    = new Document(pdf)) {

            // ── Load fonts once — iText 9 requires explicit font ──
            PdfFont bold   = PdfFontFactory.createFont(StandardFonts.HELVETICA_BOLD);
            PdfFont italic = PdfFontFactory.createFont(StandardFonts.HELVETICA_OBLIQUE);
            PdfFont normal = PdfFontFactory.createFont(StandardFonts.HELVETICA);

            // ── Header ────────────────────────────────────────────
            doc.add(new Paragraph("Patient Wellness Report")
                    .setFont(bold)
                    .setFontSize(20)
                    .setTextAlignment(TextAlignment.CENTER)
                    .setFontColor(ColorConstants.DARK_GRAY));

            doc.add(new Paragraph("Patient Wellness Monitoring System")
                    .setFont(italic)
                    .setFontSize(11)
                    .setTextAlignment(TextAlignment.CENTER)
                    .setFontColor(ColorConstants.GRAY));

            doc.add(new Paragraph(" "));

            // ── Patient details ───────────────────────────────────
            doc.add(sectionTitle("Patient Details", bold));
            Table details = new Table(2).useAllAvailableWidth();
            addRow(details, "Patient ID",   str(r.getPatientId()),   bold, normal);
            addRow(details, "Patient Name", str(r.getPatientName()), bold, normal);
            addRow(details, "Plan",         str(r.getPlanName()),    bold, normal);
            addRow(details, "Report Date",  str(r.getDate()),        bold, normal);
            addRow(details, "Generated By", "Admin ID: " + r.getGeneratedBy(), bold, normal);
            doc.add(details);

            doc.add(new Paragraph(" "));

            // ── Progress summary ──────────────────────────────────
            doc.add(sectionTitle("Progress Summary", bold));
            Table progress = new Table(2).useAllAvailableWidth();
            addRow(progress, "Total Activities",     str(r.getTotalActivities()),     bold, normal);
            addRow(progress, "Completed Activities", str(r.getCompletedActivities()), bold, normal);
            addRow(progress, "Completion %",         r.getCompletionPercentage() + "%", bold, normal);
            doc.add(progress);

            doc.add(new Paragraph(" "));

            // ── System summary ────────────────────────────────────
            doc.add(sectionTitle("System Summary", bold));
            doc.add(new Paragraph(r.getSummary())
                    .setFont(normal)
                    .setFontSize(11));

            doc.add(new Paragraph(" "));

            // ── Doctor's summary (visible to patient) ─────────────
            doc.add(sectionTitle("Doctor's Summary", bold));
            String adminNote = (r.getAdminSummary() != null && !r.getAdminSummary().isBlank())
                    ? r.getAdminSummary()
                    : "No additional summary provided by doctor.";
            doc.add(new Paragraph(adminNote)
                    .setFont(normal)
                    .setFontSize(11));

            doc.add(new Paragraph(" "));

            // ── Footer ────────────────────────────────────────────
            doc.add(new Paragraph(
                    "Generated on " + r.getDate() +
                            " | Patient Wellness Monitoring System")
                    .setFont(italic)
                    .setFontSize(9)
                    .setTextAlignment(TextAlignment.CENTER)
                    .setFontColor(ColorConstants.GRAY));

        } catch (Exception e) {
            throw new RuntimeException("PDF generation failed: " + e.getMessage(), e);
        }

        return out.toByteArray();
    }

    // ── Helpers ───────────────────────────────────────────────────

    private Paragraph sectionTitle(String title, PdfFont bold) {
        return new Paragraph(title)
                .setFont(bold)
                .setFontSize(13)
                .setFontColor(ColorConstants.DARK_GRAY);
    }

    private void addRow(Table t, String label, String value,
                        PdfFont bold, PdfFont normal) {
        t.addCell(new Cell().add(
                new Paragraph(label).setFont(bold).setFontSize(11)));
        t.addCell(new Cell().add(
                new Paragraph(value).setFont(normal).setFontSize(11)));
    }

    private String str(Object val) {
        return val != null ? val.toString() : "—";
    }
}