package com.cts.WellnessPlanManagementModule.Model;


import com.fasterxml.jackson.annotation.*;
import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.ArrayList;
import java.util.List;



@Data
@AllArgsConstructor
@NoArgsConstructor
@Entity
@Table(name = "WellnessPlan")
@JsonIdentityInfo(
        generator = ObjectIdGenerators.PropertyGenerator.class,
        property = "planId"
)
public class WellnessPlanModel
{
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long planId;

    private String planName;

    @OneToMany(mappedBy = "plan", cascade = CascadeType.ALL, orphanRemoval = true)
    private List<ActivitiesModel> activities = new ArrayList<>();


    @OneToMany(mappedBy = "wellnessPlan",cascade = CascadeType.ALL,orphanRemoval = true)
    private List<PlanAssignment> planAssignments=new ArrayList<>();

    @Override
    public String toString() {
        return "WellnessPlanModel{" +
                "planId=" + planId +
                ", planName='" + planName + '\'' +
                ", activities=" + activities +
                '}';
    }
}




/*


import com.fasterxml.jackson.annotation.JsonIdentityInfo;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.ObjectIdGenerators;
import jakarta.persistence.*;

import java.util.ArrayList;
import java.util.List;


/*
WellnessPlan Table attributes

1) planId -> autogenerated
2) planName ->
3) activities ->


@Entity
@Table(name = "WellnessPlan")
@JsonIdentityInfo(
        generator = ObjectIdGenerators.PropertyGenerator.class,
        property = "planId"

)
public class WellnessPlanModel
{

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private int planId;
    private String planName;

    @OneToMany(cascade = CascadeType.ALL,mappedBy = "plan",orphanRemoval = true)
    private List<ActivitiesModel> activities=new ArrayList<>();

    @JsonProperty(
            "assignedTo"
    )

    @OneToMany(mappedBy = "wellnessPlan",cascade = CascadeType.ALL,orphanRemoval = true)
    private List<PatientModel> patients=new ArrayList<>();

    public List<PatientModel> getPatients() {
        return patients;
    }

    public void setPatients(List<PatientModel> patients) {
        this.patients = patients;

    }

    public int getPlanId() {
        return planId;
    }

    public void setPlanId(int planId) {
        this.planId = planId;
    }

    public String getPlanName() {
        return planName;
    }

    public void setPlanName(String planName) {
        this.planName = planName;
    }

    public List<ActivitiesModel> getActivities() {
        return activities;
    }

    public void setActivities(List<ActivitiesModel> activities) {

        this.activities = activities;



    }


    @Override
    public String toString() {
        return "WellnessPlanModel{" +
                "planId=" + planId +
                ", planName='" + planName + '\'' +
                ", activities=" + activities +
                ", patients=" + patients +
                '}';
    }
}





 */