spring.application.name=wellnessplan-service

# Database
spring.datasource.url=jdbc:mysql://localhost:3306/wellness_plan_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Server
server.port=8082

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

#swagger

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

management.endpoints.web.exposure.include=health,info,metrics,env,beans,loggers,mappings
management.endpoint.health.show-details=always
management.endpoint.shutdown.enabled=true
management.endpoints.web.base-path=/actuator

info.app.name=wellnessplan-service
info.app.description=Manages wellness plans, activities and patient assignments
info.app.version=1.0.0
info.app.java-version=21
info.app.port=8082
